name = "delta-cloudflare-pages"
main = "_worker.js"
compatibility_date = "2026-05-12"

workers_dev = false
preview_urls = false

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAADP9rX4MtOkhgEpl"
TURNSTILE_EXPECTED_ACTION = "contact"
TURNSTILE_EXPECTED_HOSTNAME = "deltaintermediacoes.com.br"
CONTACT_EMAIL = "contato@deltaintermediacoes.com.br"
FROM_EMAIL = "site@deltaintermediacoes.com.br"

[assets]
directory = "./public"
binding = "ASSETS"
